server:
  port: 8081
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static
  mvc:
    view:
      prefix: /
      suffix: .html
  #连接数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssm_crud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 pageSizeZero: true     
 params: count=countSql

